services:
  projetoa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetoa-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - master_proxy_default

networks:
  master_proxy_default:
    external: true
    name: master_proxy_default  
